name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    env:
      DOTNET_NOLOGO: "true"
      DOTNET_CLI_TELEMETRY_OPTOUT: "true"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: 🔽 Setup dotnet from global.json
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          global-json-file: global.json
          dotnet-version: |
            8

      - name: 🔽 Setup just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

      - name: 🔍 Print dotnet info
        run: dotnet --info

      - name: 🧪 Test
        run: just test

      - name: 🔼 Upload packages as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: nuget
          path: artifacts/nuget/

      - name: 🔼 Upload global.json as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: global-json
          path: global.json
